export { default as CloseChatSvgIcon } from './closeChatSvgIcon.vue'
export { default as CloseSidebarSvgIcon } from './closeSidebarSvgIcon.vue'
export { default as OpenSidebarSvgIcon } from './openSidebarSvgIcon.vue'
export { default as SearchSvgIcon } from './searchSvgIcon.vue'
export { default as SendSvgIcon } from './sendSvgIcon.vue'
export { default as TickSvgIcon } from './tickSvgIcon.vue'
export { default as MessengerSvgIcon } from './messengerSvgIcon.vue'
export { default as LoadingSvgIcon } from './loadingSvgIcon.vue'
